version: '3'
tasks:
  build:
    desc: Build the default package with fancy output
    cmds:
      - nom build
  run:
    desc: Build and run the default app
    cmds:
      - nix run
  test:
    deps:
      - build
    desc: Test your project
    cmds:
      - echo TODO
  tree:
    desc: Show dependency tree of the default package
    cmds:
      - nix-tree .#default
  closure:
    desc: Show closure size of the default package
    cmds:
      - nix path-info -rsSh .#default
  fmt:
    desc: Format all code
    cmds:
      - nix fmt
  check:
    desc: Run all checks (format, build, test)
    cmds:
      - task: fmt
      - task: build
      - task: test
  default:
    cmds:
      - task -l
