version: '3'
includes:
  build:
    taskfile: ./tasks/Build.yaml
    dir: .
  lint:
    taskfile: ./tasks/Lint.yaml
    dir: .
tasks:
  init:
    cmds:
      - |
        lefthook install
    silent: true
    run: once
  watch:
    desc: Start local server with book on localhost:3000
    cmds:
      - mdbook serve
