---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tst-pod-nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location / {
            default_type text/plain;
            expires -1;
            return 200 'Server address: $server_addr:$server_port\nServer name: $hostname\nDate: $time_local\nURI: $request_uri\nRequest ID: $request_id\n';
        }
        location /public/ {
            alias /usr/share/nginx/html/;   # routage sur le point de montage
        }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tst-deployment-pvc                 # Les pvc
spec:
  storageClassName: managed-nfs-storage    # la storage classe managé
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: tst-ct-nginx
  name: tst-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      applicat: tst-pod-label-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  revisionHistoryLimit: 4
  template:                             # les template de pods
    metadata:
      labels:
        applicat: tst-pod-label-nginx
    spec:
      volumes:                              # Les volumes
        - name: nginx-configs
          configMap:                        # Une ConfigMap
            name: tst-pod-nginx-config
        - name: webpubdata                  
          persistentVolumeClaim:            # Un PVC
            claimName: tst-deployment-pvc
      containers:                           # les containers du pod
      - image: nginx:1.15
        name: tst-ct-nginx
        ports:
          - containerPort: 80
            protocol: TCP
        volumeMounts:
          - name: nginx-configs
            mountPath: /etc/nginx/conf.d
          - name: webpubdata
            mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service                      # le service
metadata:
  labels: 
    name: tst-svc-label-nginx
  name: tst-svc-nginx
spec: 
  ports:
    - port: 1080
      targetPort: 80
  selector:
    applicat: tst-pod-label-nginx
