classDiagram
  Application-A ..> CICD-A: from same git
  Application-A ..> CICD: from remote git
  Library-A ..> CICD: from remote git
  IAC-A ..> CICD: from remote git
  Application-B ..> CICD-B: from same git
  Application-B ..> CICD: from remote git
