# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_check_update = false
  config.vm.define "host" do |host|
    host.vm.network "private_network", ip: "192.168.56.20"
    host.vm.network "private_network", ip: "192.168.33.20"
    host.vm.hostname="bullseye"
    host.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.memory = 512
      v.cpus = 1
      v.check_guest_additions = false
    end
    host.vm.provision "init", type: "shell", run: "never", inline: <<-SHELL
      apt-get update
    SHELL
  end
end
