---
- name: Check that Git is installed on the server
  include_tasks: "{{ item }}"
  with_first_found:
    - "install-git_{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "install-git_{{ ansible_distribution|lower }}.yml"
    - "install-git_{{ ansible_os_family|lower }}.yml"
  
- name: Create user to run Gitea
  ansible.builtin.user: 
    name: "git"
    comment: 'Git Version Control'
    shell: "/bin/bash"
    home: "/home/git"
    
- name: create gitea var directories
  ansible.builtin.file:
    path: "{{ gitea_vardir }}/{{ item }}"
    state: "directory"
    recurse: "yes"
    owner: "git"
    group: "git"
    mode: "0750"
  with_items:
   - custom
   - data
   - log

- name: create gitea etc dir
  ansible.builtin.file:
    path: "{{ gitea_etcdir }}"
    state: "directory"
    owner: "root"
    group: "git"
    mode: "0770"

- name: download gitea binary
  ansible.builtin.get_url:
    url: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
    dest: /usr/local/bin/gitea
    owner: "root"
    group: "git"
    mode: "0755"
    validate_certs: "False"
  register: download

- name: restrict app.ini access
  ansible.builtin.file:
    path: "{{ gitea_etcdir }}/app.ini"
    mode: "0750"
  when: not download.changed

- name: deploy gitea systemd service
  ansible.builtin.template:
    src: gitea.service.j2
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: '0644'

- name: ensure gitea is started
  ansible.builtin.systemd:
    name: gitea
    state: started
    enabled: yes
