
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    hostname: ssti
    ports:
      - 127.0.0.1:5000:5000
    networks:
      - single-node_default
    volumes:
      - ./ossec.conf:/var/ossec/etc/ossec.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 
    # environment:
    #      - JOIN_MANAGER=wazuh.manager
    #      - NAME=SSTI

networks:
  single-node_default:
    external: true
